<a href="https://colab.research.google.com/github/juanmacaaz/Machine-Learning/blob/master/Tutorial_3_Clasificacion_de_Texto_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import tensorflow as tf

!pip install -q tensorflow-hub  # Libreria para reutilizacion de modulos de ML
!pip install -q tfds-nightly    # Libreria para coger datasets ya creados de manera mas comoda

import tensorflow_hub as hub
import tensorflow_datasets as tfds


print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.experimental.list_physical_devices("GPU") else "NOT AVAILABLE")



Version:  2.0.0
Eager mode:  True
Hub version:  0.7.0
GPU is NOT AVAILABLE


In [0]:
# Cargamos los datos que vamos a utilizar

train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True)

In [0]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))

# Formato de salida es
# train_labels_batch --> <tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>
# train_data         --> <tf.Tensor: shape=(10,), dtype=string, numpy=[b'I have been known to fall asleep during films, but this is us]....

In [5]:
# Para este tipo de problemas (tratar texto) nos preguntamos varias cosas
# Como represantar el texto?
# Cuantas capas usar en el modelo?
# Cuantas unidades ocultas (neuronas) usar en cada capa?

# Una forma eficiente de solucionar este problema es utilizando una tecnica de "embed" el texto a vectores
# La forma de hacer esto es mediante una red neuroal (Que la cogeremos del TF Hub)

embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1" # Ahi cogeremos el modelo
hub_layer = hub.KerasLayer(embedding, input_shape=[],                   # Creamos la capa
                           dtype=tf.string, trainable=True)

hub_layer(train_examples_batch)                                         # Transforma de texto a vextores


<tf.Tensor: id=382, shape=(3, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ],
       [ 0.71152234, -0.6353217 ,  1.7385626 , -1.1168286 , -0.5451594 ,
        -1.1808156 ,  0.09504455,  1.4653089 ,  0.66059524,  0.79308075,
        -2.2268345 ,  0.07446612, -1.4075904 , -0.70645386, -1.907037  ,
         1.4419787 ,  1.9551861 , -0.42660055, -2.8022065 ,  0.43727064]],
      dtype=float32)>